**Librerías**

In [1]:
import pandas as pd

**Lectura de datos**

In [2]:
airbnb = pd.read_csv('airbnb-listings.csv', sep = ';', decimal = '.')

**Análisis Exploratorio**

In [3]:
#TAMAÑO DEL DATASET
airbnb.shape

(14780, 89)

In [4]:
#MUESTRA DE PRIMEROS REGISTROS DEL DATASET
airbnb.head(3)

,ID,Listing Url,Scrape ID,Last Scraped,Name,Summary,Space,Description,Experiences Offered,Neighborhood Overview,...,Review Scores Communication,Review Scores Location,Review Scores Value,License,Jurisdiction Names,Cancellation Policy,Calculated host listings count,Reviews per Month,Geolocation,Features
0,15141125,https://www.airbnb.com/rooms/15141125,20170407214119,2017-04-08,Panoramic charming studio!,"Charming bright and cosy studio in ""El Rastro""...",It's a bright and cosy studio located in the h...,"Charming bright and cosy studio in ""El Rastro""...",none,The studio is located in the remarkable neighb...,...,10.0,10.0,10.0,NaN,NaN,moderate,2.0,5.11,"40.40745268477803, -3.7079954754432634","Host Is Superhost,Host Has Profile Pic,Host Id..."
1,9470166,https://www.airbnb.com/rooms/9470166,20170407214119,2017-04-08,Comfortable penthouse in the center,"In the center, recently remodeled, comfortable...",Quiet and comfortable space where you can rela...,"In the center, recently remodeled, comfortable...",none,It belongs to the district center of Madrid wh...,...,9.0,9.0,8.0,NaN,NaN,strict,13.0,5.88,"40.40831556101927, -3.705006385704201","Host Has Profile Pic,Host Identity Verified,Re..."
2,17444981,https://www.airbnb.com/rooms/17444981,20170407214119,2017-04-08,Cosy Apartment SOL/LA LATINA,Nice apartment near Sol and La Latina. Perfect...,Is a really cosy apartment with the best locat...,Nice apartment near Sol and La Latina. Perfect...,none,"La Latina is well known by El Rastro, the most...",...,10.0,10.0,10.0,NaN,NaN,moderate,1.0,6.18,"40.413722014584295, -3.7068231186536718","Host Has Profile Pic,Host Identity Verified,Re..."

In [5]:
airbnb.describe()

,ID,Scrape ID,Host ID,Host Response Rate,Host Listings Count,Host Total Listings Count,Latitude,Longitude,Accommodates,Bathrooms,...,Number of Reviews,Review Scores Rating,Review Scores Accuracy,Review Scores Cleanliness,Review Scores Checkin,Review Scores Communication,Review Scores Location,Review Scores Value,Calculated host listings count,Reviews per Month
count,1.478000e+04,1.478000e+04,1.478000e+04,12881.000000,14777.000000,14777.000000,14780.000000,14780.000000,14780.000000,14725.000000,...,14780.000000,11476.000000,11454.000000,11460.000000,11443.000000,11460.000000,11440.000000,11439.000000,14776.000000,11618.000000
mean,1.028089e+07,2.017037e+13,3.608080e+07,94.823461,12.513636,12.513636,40.497626,-3.858041,3.277808,1.281732,...,22.632273,91.697978,9.416012,9.328883,9.621778,9.647033,9.532168,9.218201,9.486871,1.870014
std,5.564829e+06,5.667971e+08,3.425360e+07,15.215988,34.090223,34.090223,4.641387,14.123146,2.097291,0.658517,...,38.290244,8.989101,0.921938,0.989933,0.802736,0.767116,0.774527,0.950578,23.626014,1.867550
min,1.862800e+04,2.016010e+13,1.745300e+04,0.000000,0.000000,0.000000,-37.851182,-123.131344,1.000000,0.000000,...,0.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.020000
25%,5.554732e+06,2.017041e+13,6.787360e+06,100.000000,1.000000,1.000000,40.409726,-3.707604,2.000000,1.000000,...,1.000000,89.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,1.000000,0.450000
50%,1.133492e+07,2.017041e+13,2.464875e+07,100.000000,2.000000,2.000000,40.419466,-3.700785,3.000000,1.000000,...,7.000000,94.000000,10.000000,10.000000,10.000000,10.000000,10.000000,9.000000,2.000000,1.200000
75%,1.532631e+07,2.017041e+13,5.432919e+07,100.000000,6.000000,6.000000,40.430916,-3.684057,4.000000,1.000000,...,27.000000,98.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,5.000000,2.780000
max,1.910969e+07,2.017062e+13,1.247534e+08,100.000000,519.000000,519.000000,55.966912,153.371427,16.000000,8.000000,...,446.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,145.000000,17.210000

In [6]:
#TODAS LAS COLUMNAS DEL DATASET
list(airbnb.columns)

['ID',
 'Listing Url',
 'Scrape ID',
 'Last Scraped',
 'Name',
 'Summary',
 'Space',
 'Description',
 'Experiences Offered',
 'Neighborhood Overview',
 'Notes',
 'Transit',
 'Access',
 'Interaction',
 'House Rules',
 'Thumbnail Url',
 'Medium Url',
 'Picture Url',
 'XL Picture Url',
 'Host ID',
 'Host URL',
 'Host Name',
 'Host Since',
 'Host Location',
 'Host About',
 'Host Response Time',
 'Host Response Rate',
 'Host Acceptance Rate',
 'Host Thumbnail Url',
 'Host Picture Url',
 'Host Neighbourhood',
 'Host Listings Count',
 'Host Total Listings Count',
 'Host Verifications',
 'Street',
 'Neighbourhood',
 'Neighbourhood Cleansed',
 'Neighbourhood Group Cleansed',
 'City',
 'State',
 'Zipcode',
 'Market',
 'Smart Location',
 'Country Code',
 'Country',
 'Latitude',
 'Longitude',
 'Property Type',
 'Room Type',
 'Accommodates',
 'Bathrooms',
 'Bedrooms',
 'Beds',
 'Bed Type',
 'Amenities',
 'Square Feet',
 'Price',
 'Weekly Price',
 'Monthly Price',
 'Security Deposit',
 'Cleaning Fee',
 'Guests Included',
 'Extra People',
 'Minimum Nights',
 'Maximum Nights',
 'Calendar Updated',
 'Has Availability',
 'Availability 30',
 'Availability 60',
 'Availability 90',
 'Availability 365',
 'Calendar last Scraped',
 'Number of Reviews',
 'First Review',
 'Last Review',
 'Review Scores Rating',
 'Review Scores Accuracy',
 'Review Scores Cleanliness',
 'Review Scores Checkin',
 'Review Scores Communication',
 'Review Scores Location',
 'Review Scores Value',
 'License',
 'Jurisdiction Names',
 'Cancellation Policy',
 'Calculated host listings count',
 'Reviews per Month',
 'Geolocation',
 'Features']

**Limpiamos las variables que no utilizaremos**

In [7]:
#CAMPOS QUE NO APORTAN, LOS ELIMINAMOS
col_drop = ['Listing Url', 'Scrape ID', 'Last Scraped', 'Name', 'Summary', 'Space', 'Description', 'Experiences Offered', 'Neighborhood Overview',
 'Notes', 'Transit', 'Access', 'Interaction', 'House Rules', 'Thumbnail Url', 'Medium Url', 'Picture Url', 'XL Picture Url', 'Host ID', 'Host URL',
 'Host Name', 'Host Location', 'Host About', 'Host Response Time', 'Host Response Rate', 'Host Acceptance Rate', 'Host Thumbnail Url', 
 'Host Picture Url', 'Host Neighbourhood', 'Host Listings Count', 'Host Total Listings Count', 'Host Verifications',  'Street',  
 'Neighbourhood', 'Neighbourhood Cleansed', 'State', 'Market', 'Smart Location', 'Country Code', 'Country',
 'Weekly Price', 'Monthly Price',  'Guests Included', 'Extra People', 'Minimum Nights', 'Maximum Nights', 'Calendar Updated',
 'Has Availability', 'Availability 30', 'Availability 60', 'Availability 90', 'Availability 365', 'Calendar last Scraped',  'First Review', 'Last Review',
 'Review Scores Accuracy', 'Review Scores Cleanliness', 'Review Scores Checkin', 'Review Scores Communication', 'Review Scores Location',
 'Review Scores Value',  'License', 'Jurisdiction Names', 'Calculated host listings count', 'Geolocation']

airbnb.drop(col_drop, axis=1, inplace=True)

In [8]:
# COLUMNAS QUE QUEDAN
list(airbnb.columns)

['ID',
 'Host Since',
 'Neighbourhood Group Cleansed',
 'City',
 'Zipcode',
 'Latitude',
 'Longitude',
 'Property Type',
 'Room Type',
 'Accommodates',
 'Bathrooms',
 'Bedrooms',
 'Beds',
 'Bed Type',
 'Amenities',
 'Square Feet',
 'Price',
 'Security Deposit',
 'Cleaning Fee',
 'Number of Reviews',
 'Review Scores Rating',
 'Cancellation Policy',
 'Reviews per Month',
 'Features']

In [9]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14780 entries, 0 to 14779
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            14780 non-null  int64
 1   Host Since                    14777 non-null  object
 2   Neighbourhood Group Cleansed  13760 non-null  object
 3   City                          14774 non-null  object
 4   Zipcode                       14274 non-null  object
 5   Latitude                      14780 non-null  float64
 6   Longitude                     14780 non-null  float64
 7   Property Type                 14780 non-null  object
 8   Room Type                     14780 non-null  object
 9   Accommodates                  14780 non-null  int64
 10  Bathrooms                     14725 non-null  float64
 11  Bedrooms                      14755 non-null  float64
 12  Beds                          14731 non-null  float64
 13  Bed Type                      14780 non-null  object
 14  Amenities                     14610 non-null  object
 15  Square Feet                   598 non-null    float64
 16  Price                         14763 non-null  float64
 17  Security Deposit              6256 non-null   float64
 18  Cleaning Fee                  8687 non-null   float64
 19  Number of Reviews             14780 non-null  int64
 20  Review Scores Rating          11476 non-null  float64
 21  Cancellation Policy           14780 non-null  object
 22  Reviews per Month             11618 non-null  float64
 23  Features                      14779 non-null  object
dtypes: float64(11), int64(3), object(10)
memory usage: 2.7+ MB

In [10]:
#ANÁLISIS DE MISSINGS
airbnb.isnull().sum().sort_values(ascending=False)
#airbnb.isna().sum().sort_values(ascending=False)

Square Feet                     14182
Security Deposit                 8524
Cleaning Fee                     6093
Review Scores Rating             3304
Reviews per Month                3162
Neighbourhood Group Cleansed     1020
Zipcode                           506
Amenities                         170
Bathrooms                          55
Beds                               49
Bedrooms                           25
Price                              17
City                                6
Host Since                          3
Features                            1
Bed Type                            0
Accommodates                        0
Room Type                           0
Property Type                       0
Number of Reviews                   0
Longitude                           0
Cancellation Policy                 0
Latitude                            0
ID                                  0
dtype: int64

In [11]:
#GUARDAMOS EL DATAFRAME MODIFICADO EN UN CSV

airbnb.to_csv("airbnb_clean.csv", index= False, sep=';')